### ISSUE TITLE
Fail to read from bigtable in dataflow

### ISSUE THREAD

**Issue by sduskis** [GoogleCloudPlatform/cloud-bigtable-client#912]
From [SO](http://stackoverflow.com/questions/38329594/fail-to-read-from-bigtable-in-dataflow):

 am using dataflow for my work to write some data into the bigtable. 
Currently, I got a task to read rows from the bigtable.
However, whenever I try to read rows from the bigtable using bigtable-hbase-dataflow, it fails and complains as follow.

>  Error:   (3218070e4dd208d3): java.lang.IllegalArgumentException: b <= a
> at org.apache.hadoop.hbase.util.Bytes.iterateOnSplits(Bytes.java:1720)
> at org.apache.hadoop.hbase.util.Bytes.split(Bytes.java:1683)
> at org.apache.hadoop.hbase.util.Bytes.split(Bytes.java:1664)
> at com.google.cloud.bigtable.dataflow.CloudBigtableIO$AbstractSource.split(CloudBigtableIO.java:512)
> at com.google.cloud.bigtable.dataflow.CloudBigtableIO$AbstractSource.getSplits(CloudBigtableIO.java:358)
> at com.google.cloud.bigtable.dataflow.CloudBigtableIO$Source.splitIntoBundles(CloudBigtableIO.java:593)
> at com.google.cloud.dataflow.sdk.runners.worker.WorkerCustomSources.performSplit(WorkerCustomSources.java:413)
> at com.google.cloud.dataflow.sdk.runners.worker.WorkerCustomSources.performSplitWithApiLimit(WorkerCustomSources.java:171)
> at com.google.cloud.dataflow.sdk.runners.worker.WorkerCustomSources.performSplit(WorkerCustomSources.java:149)
> at com.google.cloud.dataflow.sdk.runners.worker.SourceOperationExecutor.execute(SourceOperationExecutor.java:58)
> at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.executeWork(DataflowWorker.java:288)
> at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.doWork(DataflowWorker.java:221)
> at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.getAndPerformWork(DataflowWorker.java:173)
> at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.doWork(DataflowWorkerHarness.java:193)
> at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.call(DataflowWorkerHarness.java:173)
> at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.call(DataflowWorkerHarness.java:160)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> at java.lang.Thread.run(Thread.java:745)

I am using 'com.google.cloud.dataflow:google-cloud-dataflow-java-sdk-all:1.6.0' and 'com.google.cloud.bigtable:bigtable-hbase-dataflow:0.9.0' now.

**Comment by sduskis** [comment]
Do you have a sense of what your key ranges in Bigtable are?  I'm not quite sure how to reproduce this problem.

**Comment by wraith7** [comment]
Hi sduskis.
I'd like to check one thing. Do you mean bigtable family ranges? or qualifier ranges? or combined both?

**Comment by sduskis** [comment]
I man the ranges of the row keys. The problem shown in the stack trace relates to taking the set of row keys via the "Sample row keys" which roughly translate to ranges of row keys managed by individual tablet servers (a.k.a. regions in hbase) so that Dataflow can break the large job into a smaller job.  Our Dataflow connector further breaks down the range of row keys into smaller sets via the  org.apache.hadoop.hbase.util.Bytes.split() method.  In this case, Bytes.split() somehow got input from Bigtable's Sample Row Keys that doesn't seem to be correctly ordered.  I'm not sure what conditions would cause this to happen.

I'd need more information about the ranges in order to replicate the problem.  There is a way to log information about the sample row keys, which would be really useful to diagnose the issue here... I'll look that up.

**Comment by wraith7** [comment]
Thanks for the explanation sudiskis.

The row keys start with [a-z|A-Z|0-9] in normal case.
And there are 5 special keys in there.
(null)	 
-imyfone-d-back.en.softonic.com	 
.info.backend.AppTrailerRewards	 
/data/app/com.racing.moto.boat-1.apk	
婈腭Q

And all the strings charset is UTF8 and change them into the bytes as rowkeys.

If you need more information, please let me know.
Thanks a lot for your help 👍

**Comment by sduskis** [comment]
We released cloud bigtable client 0.9.2.  I think we fixed the problem with the previous change.  If you can test the fix, it would be greatly appreciated.

**Comment by wraith7** [comment]
Hi sduskis!
I tried with cloud bigtable client 0.9.2 and dataflow sdk 1.6.1.
Unfortunately, I am still seeing the same error.

`2016-08-31T01:11:43.282Z: Error:   (ac8cec38e623ac2c): java.lang.IllegalArgumentException: b <= a
	at org.apache.hadoop.hbase.util.Bytes.iterateOnSplits(Bytes.java:1720)
	at org.apache.hadoop.hbase.util.Bytes.split(Bytes.java:1683)
	at org.apache.hadoop.hbase.util.Bytes.split(Bytes.java:1664)
	at com.google.cloud.bigtable.dataflow.CloudBigtableIO$AbstractSource.split(CloudBigtableIO.java:487)
	at com.google.cloud.bigtable.dataflow.CloudBigtableIO$AbstractSource.getSplits(CloudBigtableIO.java:332)
	at com.google.cloud.bigtable.dataflow.CloudBigtableIO$Source.splitIntoBundles(CloudBigtableIO.java:561)
	at com.google.cloud.dataflow.sdk.runners.worker.WorkerCustomSources.performSplit(WorkerCustomSources.java:412)
	at com.google.cloud.dataflow.sdk.runners.worker.WorkerCustomSources.performSplitWithApiLimit(WorkerCustomSources.java:170)
	at com.google.cloud.dataflow.sdk.runners.worker.WorkerCustomSources.performSplit(WorkerCustomSources.java:148)
	at com.google.cloud.dataflow.sdk.runners.worker.SourceOperationExecutor.execute(SourceOperationExecutor.java:58)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.executeWork(DataflowWorker.java:288)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.doWork(DataflowWorker.java:221)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.getAndPerformWork(DataflowWorker.java:173)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.doWork(DataflowWorkerHarness.java:193)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.call(DataflowWorkerHarness.java:173)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.call(DataflowWorkerHarness.java:160)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

BTW, I got a warning when I start the job.
`8월 31, 2016 10:10:35 오전 com.google.cloud.dataflow.sdk.runners.dataflow.CustomSources serializeToCloudSource
Warning: Size estimation of the source failed: com.google.cloud.bigtable.dataflow.CloudBigtableIO$Source@61526469
java.lang.IllegalStateException: Neither Jetty ALPN nor OpenSSL via netty-tcnative were properly configured.
	at com.google.bigtable.repackaged.com.google.cloud.grpc.BigtableSession.<init>(BigtableSession.java:256)
	at com.google.cloud.bigtable.dataflow.CloudBigtableIO$AbstractSource.getSampleRowKeys(CloudBigtableIO.java:394)
	at com.google.cloud.bigtable.dataflow.CloudBigtableIO$Source.getSampleRowKeys(CloudBigtableIO.java:522)
	at com.google.cloud.bigtable.dataflow.CloudBigtableIO$Source.getEstimatedSizeBytes(CloudBigtableIO.java:585)
	at com.google.cloud.dataflow.sdk.runners.dataflow.CustomSources.serializeToCloudSource(CustomSources.java:95)
	at com.google.cloud.dataflow.sdk.runners.dataflow.ReadTranslator.translateReadHelper(ReadTranslator.java:64)
	at com.google.cloud.dataflow.sdk.runners.dataflow.ReadTranslator.translate(ReadTranslator.java:43)
	at com.google.cloud.dataflow.sdk.runners.dataflow.ReadTranslator.translate(ReadTranslator.java:40)
	at com.google.cloud.dataflow.sdk.runners.DataflowPipelineTranslator$Translator.visitTransform(DataflowPipelineTranslator.java:513)
	at com.google.cloud.dataflow.sdk.runners.TransformTreeNode.visit(TransformTreeNode.java:219)
	at com.google.cloud.dataflow.sdk.runners.TransformTreeNode.visit(TransformTreeNode.java:215)
	at com.google.cloud.dataflow.sdk.runners.TransformHierarchy.visit(TransformHierarchy.java:102)
	at com.google.cloud.dataflow.sdk.Pipeline.traverseTopologically(Pipeline.java:259)
	at com.google.cloud.dataflow.sdk.runners.DataflowPipelineTranslator$Translator.translate(DataflowPipelineTranslator.java:462)
	at com.google.cloud.dataflow.sdk.runners.DataflowPipelineTranslator.translate(DataflowPipelineTranslator.java:146)
	at com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner.run(DataflowPipelineRunner.java:561)
	at cle.cloud.dataflow.sdk.runners.BlockingDataflowPipelineRunner.run(BlockingDataflowPipelineRunner.java:95)
	at com.google.cloud.dataflow.sdk.runners.BlockingDataflowPipelineRunner.run(BlockingDataflowPipelineRunner.java:56)
	at com.google.cloud.dataflow.sdk.Pipeline.run(Pipeline.java:180)`
Is this warning related to this issue?

**Comment by dhjeon** [comment]
@sduskis, any progress here?

We have this issue only in a single table (out of four), so it seems it is related to the rowkey value issue you mentioned. If you need more info to reproduce the problem (e.g. bigtable instance, project id, etc), please contact jeon@molocoads.com. 

BTW, if we get rid of those problematic keys, it might work? If it is the case, I will simply get rid of those rows @wraith7 provided and try again. Thanks!

**Comment by sduskis** [comment]
I added a try/catch around the offending code.  I'll release a new 0.9.3-SNAPSHOT tomorrow with this fix.

**Comment by sduskis** [comment]
Since I can't reproduce this problem, I hope you can test 0.9.3-SNAPSHOT once it's rolled out.  I hope it works.

**Comment by sduskis** [comment]
I deployed the 0.9.3-SNAPSHOT. Can you please test?

**Comment by dhjeon** [comment]
Thank you for the quick follow-up. I'll try today.

Would you enlighten me how to use the 0.9.3-SNAPSHOT? (Sorry if this is a very basic question, I'm a newbie in maven and gradle..)

I don't see it here: https://mvnrepository.com/artifact/com.google.cloud.bigtable/bigtable-hbase-dataflow

We're using gradle and the dependencies look like this:
```
repositories {
    mavenCentral()
}

dependencies {
    compile 'com.fasterxml.jackson.core:jackson-core:2.4.2'
    compile 'com.fasterxml.jackson.core:jackson-annotations:2.4.2'
    compile 'com.google.apis:google-api-services-bigquery:v2-rev322-1.22.0'
    compile 'com.google.apis:google-api-services-storage:v1-rev84-1.22.1'
    compile 'com.google.cloud.bigtable:bigtable-hbase-dataflow:0.9.2'
    compile 'com.google.cloud.dataflow:google-cloud-dataflow-java-sdk-all:1.7.0'
    compile 'com.google.code.gson:gson:2.5'
    compile 'com.google.guava:guava:19.0'
    compile 'com.google.http-client:google-http-client-jackson2:1.19.0'
    compile 'com.google.protobuf:protobuf-java:3.0.2'
    compile 'commons-httpclient:commons-httpclient:2.0.2'
    compile 'commons-codec:commons-codec:1.6'
    compile 'commons-io:commons-io:2.5'
    compile 'io.netty:netty-tcnative-boringssl-static:1.1.33.Fork22'
    compile 'org.apache.commons:commons-lang3:3.4'
    compile 'org.slf4j:slf4j-api:1.7.7'
    compile 'org.slf4j:slf4j-jdk14:1.7.7'
    compile 'org.glassfish:javax.json:1.0.4'
    testCompile 'org.hamcrest:hamcrest-all:1.3'
    testCompile 'junit:junit:4.12'
}
```

**Comment by sduskis** [comment]
You have to add the following to your pom.xml:
```
  <repositories>
    <repository>
      <id>snapshots-repo</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <releases><enabled>false</enabled></releases>
      <snapshots><enabled>true</enabled></snapshots>
    </repository>
  </repositories>
```
[Here's](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/blob/master/java/hello-world/pom.xml) a full pom.xml with that snippet included.

**Comment by sduskis** [comment]
[It looks like](http://dogwood008.github.io/kotlin-web-site-ja/using-gradle.html), this might work:

```
repositories {
    mavenCentral()
    maven {
       url 'http://oss.sonatype.org/content/repositories/snapshots'
    }
}
```

**Comment by dhjeon** [comment]
Now the error has gone! Thanks a lot.

What's surprising to me was that it worked not only with 0.9.3-SNAPSHOT but also with 0.9.2. Is this expected? I tried 0.9.2 yesterday and it didn't work.

**Comment by sduskis** [comment]
The problem seems to be data driven.  The data may have changed.  0.9.3-SNAPSHOT adds more defensive code.  It's unfortunate that we were not able to pinpoint the specific problem :(

**Comment by sduskis** [comment]
That said, I'm glad this is fixed!

**Comment by dhjeon** [comment]
It is somewhat surprising to me that the data issue was there for more than one month and has gone today...But anyway, thanks a lot for your help - deeply appreciated. If this problem happens again, I'll report.

**Comment by sduskis** [comment]
I know what you mean.  I can't explain it either, and am both surprised and happy that the issue is resolved.

**Comment by dhjeon** [comment]
I think I found the root cause.

Previously, our build file omitted this dependency:
```compile 'io.netty:netty-tcnative-boringssl-static:1.1.33.Fork22'```

Today, I added the dependency and it resolved all the issues. I double-checked that the problem arises without the dependency. Hope this helps.
